services:
  - type: web
    name: svamitva-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    healthCheckPath: /api
    envVars:
      - key: PORT
        value: 10000
      - key: HF_MODEL_REPO_UNET
        value: holypreet/svamitva-unet-weights
      - key: HF_MODEL_REPO_EFFICIENTNET
        value: holypreet/svamitva-unet-weights
      - key: HF_HUB_ENABLE
        value: "true"
      - key: DISABLE_PYTORCH
        value: "1"
      - key: HF_TOKEN
        sync: false


